import { MakeLogicType, actions, kea, key, listeners, path, props, reducers, selectors } from 'kea'

import posthog from 'lib/posthog-typed'

export type ExceptionCardLogicProps = {
    issueId: string
    loading: boolean
}

export type ExceptionCardTab = 'stack_trace' | 'properties' | 'session'
export type ExceptionCardSessionTab = 'timeline' | 'recording'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface exceptionCardLogicValues {
    currentSessionTab: ExceptionCardSessionTab
    currentTab: ExceptionCardTab
    expandedFrameRawIds: Set<string>
    issueId: string
    loading: boolean
    showAdditionalProperties: boolean
    showJSONProperties: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface exceptionCardLogicActions {
    setCurrentSessionTab: (tab: ExceptionCardSessionTab) => {
        tab: ExceptionCardSessionTab
    }
    setCurrentTab: (tab: ExceptionCardTab) => {
        tab: ExceptionCardTab
    }
    setFrameExpanded: (
        rawId: string,
        expanded: boolean
    ) => {
        expanded: boolean
        rawId: string
    }
    setShowAdditionalProperties: (showProperties: boolean) => {
        showProperties: boolean
    }
    setShowJSONProperties: (showJSON: boolean) => {
        showJSON: boolean
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface exceptionCardLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        issueId: (issueId: string) => string
        loading: (loading: boolean) => boolean
    }
}

export type exceptionCardLogicType = MakeLogicType<
    exceptionCardLogicValues,
    exceptionCardLogicActions,
    ExceptionCardLogicProps,
    exceptionCardLogicMeta
>

export const exceptionCardLogic = kea<exceptionCardLogicType>([
    path((key) => ['products', 'error_tracking', 'ExceptionCard', key]),
    key((props) => props.issueId),
    props({} as ExceptionCardLogicProps),

    actions({
        setShowJSONProperties: (showJSON: boolean) => ({ showJSON }),
        setShowAdditionalProperties: (showProperties: boolean) => ({ showProperties }),
        setCurrentSessionTab: (tab: ExceptionCardSessionTab) => ({ tab }),
        setCurrentTab: (tab: ExceptionCardTab) => ({ tab }),
        setFrameExpanded: (rawId: string, expanded: boolean) => ({ rawId, expanded }),
    }),

    reducers({
        expandedFrameRawIds: [
            new Set<string>(),
            {
                setFrameExpanded: (state, { rawId, expanded }) => {
                    const has = state.has(rawId)
                    if (expanded === has) {
                        return state
                    }
                    const next = new Set(state)
                    if (expanded) {
                        next.add(rawId)
                    } else {
                        next.delete(rawId)
                    }
                    return next
                },
            },
        ],
        showJSONProperties: [
            false,
            {
                setShowJSONProperties: (_, { showJSON }) => showJSON,
            },
        ],
        showAdditionalProperties: [
            true,
            {
                setShowAdditionalProperties: (_, { showProperties }) => showProperties,
            },
        ],
        currentSessionTab: [
            'timeline' as ExceptionCardSessionTab,
            {
                setCurrentSessionTab: (_, { tab }) => tab,
            },
        ],
        currentTab: [
            'stack_trace' as ExceptionCardTab,
            {
                setCurrentTab: (_, { tab }) => tab,
            },
        ],
    }),

    selectors({
        issueId: [(_, p) => [p.issueId], (issueId: string) => issueId],
        loading: [(_, p) => [p.loading], (loading: boolean) => loading],
    }),

    listeners(({ props }) => ({
        setFrameExpanded: ({ expanded }) => {
            if (expanded) {
                posthog.capture('error_tracking_stacktrace_explored', { issue_id: props.issueId })
            }
        },
    })),
])
