import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from '@posthog/lemon-ui'

import { OrganizationMembershipLevel } from 'lib/constants'
import { membersLogic } from 'scenes/organization/membersLogic'
import { organizationLogic } from 'scenes/organizationLogic'
import { userLogic } from 'scenes/userLogic'

import type { OrganizationType, UserType } from '~/types'

import { conversationsAvailabilityList, conversationsAvailabilityUpdate } from './generated/api'
import type { AgentAvailabilityApi } from './generated/api.schemas'

export interface SetAgentAvailabilityPayload {
    userId: number
    isAvailable: boolean
    /** Omit to leave the stored group as it is, so a toggle can't wipe a choice we haven't loaded. */
    handoffRoleId?: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface agentAvailabilityLogicValues {
    currentOrganization: OrganizationType | null // organizationLogic
    user: UserType | null // userLogic
    availability: AgentAvailabilityApi[]
    availabilityByUserId: Record<number, AgentAvailabilityApi>
    availabilityLoading: boolean
    canSetOthers: boolean
    myAvailability: AgentAvailabilityApi | null
    myHandoffRoleId: string | null
    unavailableUserIds: Set<number>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface agentAvailabilityLogicActions {
    ensureAllMembersLoaded: () => {
        value: true
    } // membersLogic
    loadCurrentOrganizationSuccess: (
        currentOrganization: OrganizationType | null,
        payload?: any
    ) => {
        currentOrganization: OrganizationType | null
        payload?: any
    } // organizationLogic
    loadAvailability: () => any
    loadAvailabilityFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAvailabilitySuccess: (
        availability: AgentAvailabilityApi[],
        payload?: any
    ) => {
        availability: AgentAvailabilityApi[]
        payload?: any
    }
    setAgentAvailability: (payload: SetAgentAvailabilityPayload) => {
        payload: SetAgentAvailabilityPayload
    }
    setAgentAvailabilityFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    setAgentAvailabilitySuccess: (
        availability: AgentAvailabilityApi[],
        payload?: {
            payload: SetAgentAvailabilityPayload
        }
    ) => {
        availability: AgentAvailabilityApi[]
        payload?: {
            payload: SetAgentAvailabilityPayload
        }
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface agentAvailabilityLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        availabilityByUserId: (availability: AgentAvailabilityApi[]) => Record<number, AgentAvailabilityApi>
        unavailableUserIds: (availability: AgentAvailabilityApi[]) => Set<number>
        myAvailability: (
            availabilityByUserId: Record<number, AgentAvailabilityApi>,
            user: UserType | null
        ) => AgentAvailabilityApi | null
        myHandoffRoleId: (myAvailability: AgentAvailabilityApi | null) => string | null
        canSetOthers: (currentOrganization: OrganizationType | null) => boolean
    }
}

export type agentAvailabilityLogicType = MakeLogicType<
    agentAvailabilityLogicValues,
    agentAvailabilityLogicActions,
    Record<string, any>,
    agentAvailabilityLogicMeta
>

export const agentAvailabilityLogic = kea<agentAvailabilityLogicType>([
    path(['products', 'conversations', 'frontend', 'agentAvailabilityLogic']),
    connect(() => ({
        values: [organizationLogic, ['currentOrganization'], userLogic, ['user']],
        actions: [membersLogic, ['ensureAllMembersLoaded'], organizationLogic, ['loadCurrentOrganizationSuccess']],
    })),
    actions({
        setAgentAvailability: (payload: SetAgentAvailabilityPayload) => ({ payload }),
    }),
    loaders(({ values }) => ({
        availability: [
            [] as AgentAvailabilityApi[],
            {
                loadAvailability: async () => {
                    const organizationId = values.currentOrganization?.id
                    if (!organizationId) {
                        return []
                    }
                    return await conversationsAvailabilityList(organizationId)
                },
                setAgentAvailability: async ({ payload }) => {
                    const organizationId = values.currentOrganization?.id
                    if (!organizationId) {
                        return values.availability
                    }
                    await conversationsAvailabilityUpdate(organizationId, payload.userId, {
                        is_available: payload.isAvailable,
                        ...(payload.handoffRoleId !== undefined ? { handoff_role_id: payload.handoffRoleId } : {}),
                    })
                    // Refetch rather than patch the row in place: the response carries the new state
                    // but not the resolved group name or who changed it, both of which the roster shows.
                    return await conversationsAvailabilityList(organizationId)
                },
            },
        ],
    })),
    selectors({
        availabilityByUserId: [
            (s) => [s.availability],
            (availability: AgentAvailabilityApi[]): Record<number, AgentAvailabilityApi> =>
                Object.fromEntries(availability.map((entry) => [entry.user.id, entry])),
        ],
        // Absence of a row means available, so only rows that say otherwise count.
        unavailableUserIds: [
            (s) => [s.availability],
            (availability: AgentAvailabilityApi[]): Set<number> =>
                new Set(availability.filter((entry) => !entry.is_available).map((entry) => entry.user.id)),
        ],
        myAvailability: [
            (s) => [s.availabilityByUserId, s.user],
            (
                availabilityByUserId: Record<number, AgentAvailabilityApi>,
                user: UserType | null
            ): AgentAvailabilityApi | null => (user ? (availabilityByUserId[user.id] ?? null) : null),
        ],
        myHandoffRoleId: [
            (s) => [s.myAvailability],
            (myAvailability: AgentAvailabilityApi | null): string | null => myAvailability?.handoff_role?.id ?? null,
        ],
        canSetOthers: [
            (s) => [s.currentOrganization],
            (currentOrganization: OrganizationType | null): boolean =>
                (currentOrganization?.membership_level ?? OrganizationMembershipLevel.Member) >=
                OrganizationMembershipLevel.Admin,
        ],
    }),
    listeners(({ actions }) => ({
        // afterMount can land before the organization resolves, and every request here is nested
        // under its id. Without this the list stays silently empty and nobody is marked unavailable.
        loadCurrentOrganizationSuccess: () => {
            actions.loadAvailability()
        },
        setAgentAvailabilityFailure: ({ error }: { error: string }) => {
            lemonToast.error(error || "Couldn't save availability. Try again.")
        },
        // Without this the failure is invisible and reads as "everyone is available", which quietly
        // stops the assignee picker marking anyone.
        loadAvailabilityFailure: () => {
            lemonToast.error("Couldn't load who's available. Reload the page to try again.")
        },
    })),
    afterMount(({ actions }) => {
        actions.loadAvailability()
        // membersLogic only loads on request, and the roster is a row per member, so ask for them.
        actions.ensureAllMembersLoaded()
    }),
])
