# Generated by Django 5.2.17 on 2026-08-14 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0090_taskworkflowdispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskworkflowdispatch",
            name="enqueued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
